version: '3'
services:

  dcardenascom-nginx:
    image: nginx:1.23.1-alpine
    depends_on:
      - dcardenascom-web
      - dcardenascom-ghost
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/prod:/etc/nginx/conf.d
      - dcardenascom-web:/var/www/dcardenascom-web
    container_name: dcardenascom-nginx
    logging:
      options:
        max-size: 50m
    networks:
      dcardenascom-network:
        aliases:
          - dcardenascom-nginx

  dcardenascom-web:
    image: node:16-alpine3.15
    volumes:
      - ./repos/dcardenascom-web/.:/home/node/app
      - dcardenascom-web:/home/node/app/dist
    container_name: dcardenascom-web
    working_dir: /home/node/app
    command: sh -c "apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.14/main ca-certificates && apk update && apk add python3 make g++ certbot certbot-nginx && NODE_OPTIONS=--openssl-legacy-provider && make install && make start"
    logging:
      options:
        max-size: 50m
    networks:
      dcardenascom-network:
        aliases:
          - dcardenascom-web

  dcardenascom-ghost:
    image: ghost:5.52.3-alpine
    container_name: dcardenascom-ghost
    env_file:
      - .env
    environment:
      database__client: mysql
      database__connection__host: dcardenascom-mysql
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ghost
      url: http://0.0.0.0:80
    volumes:
      - dcardenascom-ghost:/var/lib/ghost/content
      - ./config/ghost/config.production.json:/var/lib/ghost/config.production.json:ro
    networks:
      dcardenascom-network:
        aliases:
          - dcardenascom-ghost

  dcardenascom-mysql:
    image: mysql:latest
    container_name: dcardenascom-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ghost
    volumes:
      - dcardenascom-mysql:/var/lib/mysql
    networks:
      dcardenascom-network:
        aliases:
          - dcardenascom-mysql

networks:
  dcardenascom-network:

volumes:
  dcardenascom-web:
  dcardenascom-mysql:
  dcardenascom-ghost:
