version: '3'
services:

  dcardenascom-nginx:
    image: nginx:1.23.1-alpine
    depends_on:
      - dcardenascom-web
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - dcardenascom-web:/var/www/dcardenascom-web
    container_name: dcardenascom-nginx
    logging:
      options:
        max-size: 50m
    networks:
      dcardenascom-network:
        aliases:
          - dcardenascom-nginx

  dcardenascom-web:
    image: node:16-alpine3.15
    volumes:
      - ./repos/dcardenascom-web/.:/home/node/app
      - dcardenascom-web:/home/node/app/dist
    container_name: dcardenascom-web
    working_dir: /home/node/app
    command: sh -c "export NODE_OPTIONS=--openssl-legacy-provider && apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.14/main ca-certificates && apk update && apk add python3 make g++ && NODE_OPTIONS=--openssl-legacy-provider && make install && make start"
    logging:
      options:
        max-size: 50m
    networks:
      dcardenascom-network:
        aliases:
          - dcardenascom-web

  dcardenascom-qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: dcardenascom-qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=80
    volumes:
      - dcardenascom-qbittorrent:/config
      - ./data:/downloads
    ports:
      - 80:80
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

networks:
  dcardenascom-network:

volumes:
  dcardenascom-web:
  dcardenascom-qbittorrent:
